In [41]:
import pandas as pd
import numpy as np
df = pd.read_csv('../Analyze_Data/penguins.csv')
df.head(5)
# df.tail(5)
# df.info()
# df.describe()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Gentoo,Torgersen,35.6,15.5,184,3271,male
1,Gentoo,Dream,57.3,13.8,197,2830,male
2,Adelie,Torgersen,40.8,18.4,205,3514,female
3,Adelie,Biscoe,49.7,20.3,170,5808,male
4,Gentoo,Biscoe,43.5,14.4,218,4078,male

In [29]:
# #6
# print((df['species']))
# #7
# print(df[["species", "body_mass_g"]])
#8
# print(df.iloc[9])
#9
# print(df.iloc[4:10])
#10
print(df[["bill_length_mm", "bill_depth_mm"]])

    bill_length_mm  bill_depth_mm
0             35.6           15.5
1             57.3           13.8
2             40.8           18.4
3             49.7           20.3
4             43.5           14.4
5             37.4           20.6
6             48.4           21.8
7             57.1           16.3
8             40.7           15.6
9             41.9           18.7
10            51.8           19.3
11            39.3           19.6
12            52.2           15.0
13            55.1           16.6
14            47.5           21.0
15            41.2           18.1
16            44.0           22.0
17            56.5           14.4
18            44.6           18.4
19            52.0           14.0
20            37.8           16.9
21            47.7           14.0
22            54.1           17.9
23            47.2           14.0
24            41.0           18.1
25            54.1           14.2
26            56.8           16.8
27            45.0           19.0
28            40.6           16.0
29            35.2           19.4

In [30]:
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Gentoo,Torgersen,35.6,15.5,184,3271,male
1,Gentoo,Dream,57.3,13.8,197,2830,male
2,Adelie,Torgersen,40.8,18.4,205,3514,female
3,Adelie,Biscoe,49.7,20.3,170,5808,male
4,Gentoo,Biscoe,43.5,14.4,218,4078,male

In [62]:
# df[df["species"] == "Gentoo"]
#df[df['sex'] == 'female']
#df[df['body_mass_g'] > 5000]
#df[df['bill_length_mm'] > 45]
#df[(df['species'] == 'Gentoo') & (df['body_mass_g'] > 5000)]
#df[(df['sex'] == 'male') & (df['flipper_length_mm'] > 200)]
#df[(df['species'] == 'Adelie') | (df['species'] == 'Chinstrap')]
#df[(df['bill_length_mm'] > 45) & (df['bill_depth_mm'] > 18)]
df[(df['body_mass_g'] > 5000) | (df['flipper_length_mm'] > 220)]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
3,Adelie,Biscoe,49.7,20.3,170,5808,male
7,Gentoo,Dream,57.1,16.3,182,5585,male
8,Adelie,Dream,40.7,15.6,175,6203,male
10,Chinstrap,Torgersen,51.8,19.3,213,5354,male
12,Chinstrap,Dream,52.2,15.0,190,6152,male
15,Chinstrap,Torgersen,41.2,18.1,186,5759,female
17,Adelie,Torgersen,56.5,14.4,180,5944,female
19,Gentoo,Torgersen,52.0,14.0,226,4899,female
23,Gentoo,Biscoe,47.2,14.0,193,6299,female